Lake breeze Case Study
CROCUS-Urban/instrument-cookbooks pull request #31
Opened 2023-05-22 21:30 UTC by jrobrien91

- notebook outlining a lake breeze from 7 May 2023 which coincides with the start of the NEIU dataset
- outlines displaying NEXRAD reflectivity data from KLOT with Vaisala AQT data from NEIU node (W08D)
- creates gif of images for display

2023-05-22 21:35 UTC, mgrover1 approved these changes

2023-05-22 21:36 UTC, mgrover1 requested changes
It looks like a link check failed...

2023-05-22 21:39 UTC, jrobrien91 commented
@mgrover1 The AMS glossary link failed but works locally. Any thoughts on trying to debug?

(notebooks/case-study/lake-breeze-ci: line 10004) broken    **https://glossary.ametsoc.org/wiki/Lake_breeze** - HTTPSConnectionPool(host='glossary.ametsoc.org', port=443): Max retries exceeded with url: /wiki/Lake_breeze (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

2023-05-23 00:11 UTC, jrobrien91 commented
@mgrover1 I removed the AMS glossary link

2023-05-23 14:48 UTC, merged